### ISSUE TITLE
ctrl+f is mapped but ctrl+s isn't.  How to undo install?

### ISSUE THREAD

**Issue by notuntoward** [kpe/jupyterlab-emacskeys#2]
I've just tried this out on Windows 10 chrome and am having mixed results.  

I see that ctrl+f is now mapped to "character forward" like it is in emacs.  This overwrites the default ctrl+f, which is search by default.  That would be fine if search was also mapped like in emacs, but unfortunately, ctrl+s is still mapped to "save notebook".

There's no longer anyway to search.  

ctrl+e and ctrl+a are sucessfully mapped like in emacs but a lot of other standard emacs keys combinations are not mapped, for example, ctrl+n, ctrl+b,...

**Comment by kpe** [comment]
some keybindigs are taken by the browser (like ctrl+n), for those binding you could set an Emacs key-theme for all GTK applications (see the README). Other keybindings like Ctrl+F or Ctrl+P are mappen inside jupyterlab - those you could redefine or disable.
