### ISSUE TITLE
Please make it compatible with Jupyterlab >3.0

### ISSUE THREAD

**Issue by 0liu** [kpe/jupyterlab-emacskeys#9]
Great extension! Thank you for making it. Unfortunately this only works with v2.x, while other new extensions only work with 3.x. It seems there is an discussion [#3885](https://github.com/jupyterlab/jupyterlab/issues/3885) on emacs key binding coming with v3.x, but we don't know when it could happen. Can you please make this extension working with v3.x as well? At least we could have a workaround before the feature is built in v3.x.

**Comment by spencerahill** [comment]
Pinging this.  I love my emacs keybindings so much that I will probably downgrade jupyterlab back to v2 until this is supported again :)

**Comment by 0liu** [comment]
Currently the best bet is vscode. It has implemented notebook keybinding in its insider version, but not released yet. See [vscode issue 1447](https://github.com/microsoft/vscode-jupyter/issues/1447). I don't think this will be resolved so close it now.

**Comment by spencerahill** [comment]
@0liu I'm not switching to VSCode for this, and the package author may ultimately address this.  So I don't think it makes sense to close this.  Please re-open.  Thanks.

**Comment by 0liu** [comment]
> @0liu I'm not switching to VSCode for this, and the package author may ultimately address this. So I don't think it makes sense to close this. Please re-open. Thanks.

If the author @kpe would like to address this, the author surely can reopen it.
